#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PCAapp.Resource", IsApplication=true)]

namespace PCAapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int ButtonText = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int HelpBtn = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int MainMenuBG = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MainMenuBtn = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Title = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cameraBtnImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cropBtnImage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int importFileImage = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int infoBtnImage = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int infoBtnImage2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pca = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int chooseMode = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int cropButton = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int finishButton = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int helpButton = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int imageView = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int labelButton = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int numberOfPicturesLbl = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int picButton = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int pictureTitleLbl = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int profButton = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int selectAreaCounterLbl = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int selectAreaTitle = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int studentButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int titleLbl = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AreaSelection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProfessorMode = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int StudentMode = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TakePicture = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int Student_Mode = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int finishButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int goBackButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int picButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int profButton = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int profFinishbutton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int takeapicprof = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
